-- This specification was automatically generated by the AURA CLI
-- DO NOT MODIFY

package AURA with Pure is

    type Repository_Format is (system, local, git);

    Platform_Family       : constant String := "unix";
    Platform_Flavor       : constant String := "darwin";
    Platform_Version      : constant String := "20.5.0";
    Platform_Architecture : constant String := "x86";

end AURA;
